# Generated by Django 4.1.3 on 2022-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='random image', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
